### ISSUE TITLE
I would like to ask how long it takes for such an experiment to run a type of noise, and the minimum equipment requirements

### ISSUE THREAD

**Issue by guandachen** [madhavmk/Noise2Noise-audio_denoising_without_clean_training_data#1]
I would like to ask how long it takes for such an experiment to run a type of noise, and the minimum equipment requirements,Thanks!!

**Comment by anujstam** [comment]
Hi.
It took us about 48 hours on an Nvidia K80 per noise type + training method - this is the same GPU available on Colab or on Azure data science VMs. For our exact network and dataset, you will need 12 GB of GPU memory.
If you're looking to test it faster, you could use the smaller DCUnet10 model but we did not test with those, or alternatively you could use a different dataset.

**Comment by guandachen** [comment]
> 你好。
> 在Nvidia K80上，每種噪聲類型+訓練方法花了我們大約48小時-這與Colab或Azure數據科學VM上可用的GPU相同。對於我們確切的網絡和數據集，您將需要12 GB的GPU內存。
> 如果您想更快地測試它，可以使用較小的DCUnet10模型，但我們沒有對此進行測試，或者可以使用其他數據集。

ok,thanks,i will try on the colab
