### ISSUE TITLE
requirements.txt for Linux 

### ISSUE THREAD

**Issue by HarisNaveed17** [madhavmk/Noise2Noise-audio_denoising_without_clean_training_data#3]
Hello,
First of all great work!

Can you please add a requirements.txt file for linux as well? The present one does not work directly with the conda create command. This may also be because a lot of packages require channels different from the base channels, if you can specify those channels in the readme that would make it more convenient.

Thank you!

**Comment by madhavmk** [comment]
Hey,

We use just 2 conda channels: conda-forge and defaults.
You are env creation fails because I generated the YAML using Windows platform , but you are transferring across to Linux platform. Solution is to omit build info
Convert "cryptography=3.4.7=py38hd7da0ea_0" -> "cryptography=3.4.7" and so on

**Comment by HarisNaveed17** [comment]
I already did that but it says the following packages are not available from either channel:
  - m2w64-libwinpthread-git==5.0.0.4634.697f757
  - m2w64-gmp==6.1.0
  - pypesq==1.2.4
  - m2w64-gcc-libs==5.3.0
  - pystoi==0.3.3
  - msys2-conda-epoch==20160418
  - pesq==0.0.2
  - vs2015_runtime==14.28.29325
  - vc==14.2
  - m2w64-gcc-libgfortran==5.3.0
  - m2w64-gcc-libs-core==5.3.0

I haven't done development work on Windows so not sure if these packages are platform specific, in that case it makes sense that they're not available on the linux-64 channel. Can you please confirm?

Thanks!

**Comment by madhavmk** [comment]
No issue. If the library is not on conda, try pip installing them manually one by one.
