### ISSUE TITLE
Saved audio file length

### ISSUE THREAD

**Issue by joeoct93** [madhavmk/Noise2Noise-audio_denoising_without_clean_training_data#5]
Hello, I've been trying out your noise2noise denoising on jupyter notebook, and I found that the audio saved is locked to 3 seconds, even if the audio processed is more than 3 seconds long. Is there a way to control this? Thank you.

**Comment by madhavmk** [comment]
Hello @joeoct93, sorry for the late reply
Yes, we are cutting/padding audios in the datasets to `165000` numpy array length, which equates to `165000/48000 = 3.4` seconds on a 48khz sample rate.
This fixed length can be modified by setting `self.max_len` attribute in the `SpeechDataset` class.
