### ISSUE TITLE
STFT requires return_complex = True

### ISSUE THREAD

**Issue by guardinger-ashish-nagarse** [madhavmk/Noise2Noise-audio_denoising_without_clean_training_data#7]
I am getting this error 

RuntimeError: stft requires the return_complex parameter be given for real inputs, and will further require that return_complex=True in a future PyTorch release.

on running 
train_losses, test_losses = train(dcunet20, train_loader, test_loader, loss_fn, optimizer, scheduler, 4)

this cell. 

I am using pytorch on GPU which support CUDA-11.7 , python-3.11

**Comment by guardinger-ashish-nagarse** [comment]
anf after i am specifying return_complex = True in torch.stft(........................ , return_complex = True)

i am getting new error

RuntimeError: Input type (struct c10::complex<float>) and bias type (float) should be the same

**Comment by guardinger-ashish-nagarse** [comment]
I am able to run it completely in an env with py-3.8.18 and pytorch-1.10 with cuda-11.3 
but It throws error with latest version of pytorch : ) 
How can i solve those??? I am stuck :)
Thank you.

**Comment by anujstam** [comment]
Looks like by default stft in torch 1.10 has return_complex set to None, so the imaginary terms are stored separately. For newer versions of Torch, you probably need to add torch.view_as_real() [as per the documentation](https://pytorch.org/docs/stable/generated/torch.stft.html)  after the stft to go from complex to real
